# Generated by Django 4.1 on 2022-12-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='企业名称')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('logo', models.ImageField(upload_to='company', verbose_name='LOGO')),
                ('introduce', models.TextField(max_length=400, verbose_name='企业简介')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=20)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='注册日期')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业列表',
                'ordering': ['-created_date'],
            },
        ),
    ]
