# Generated by Django 4.1 on 2022-12-30 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comment_count_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=9000, verbose_name='评论数量'),
            preserve_default=False,
        ),
    ]
