# Generated by Django 4.1 on 2023-01-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_tag_company_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comment_count_num',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
    ]
