# Generated by Django 4.1 on 2022-12-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='username',
            new_name='name',
        ),
    ]
